CREATE DATABASE QL_CLB;
GO
USE QL_CLB;
GO

CREATE TABLE TAI_KHOAN (
    MaTaiKhoan INT IDENTITY(1,1) PRIMARY KEY,
    TenTaiKhoan NVARCHAR(100) NOT NULL,
    MatKhau NVARCHAR(255) NOT NULL,
    VaiTro NVARCHAR(50),
    TrangThai NVARCHAR(50),
    NgayTao DATETIME DEFAULT GETDATE()
);

CREATE TABLE BAN (
    MaBan INT IDENTITY(1,1) PRIMARY KEY,
    TenBan NVARCHAR(150) NOT NULL
);

CREATE TABLE NHOM (
    MaNhom INT IDENTITY(1,1) PRIMARY KEY,
    TenNhom NVARCHAR(150) NOT NULL
);

CREATE TABLE NGUOI_DUNG (
    MaNguoiDung INT IDENTITY(1,1) PRIMARY KEY,
    MaTaiKhoan INT UNIQUE,
    HoTen NVARCHAR(150),
    SoDienThoai NVARCHAR(20),
    Email NVARCHAR(150),
    DiaChi NVARCHAR(255),
    NgaySinh DATE,
    MaBan INT NULL,
    MaNhom INT NULL,
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN(MaTaiKhoan),
    FOREIGN KEY (MaBan) REFERENCES BAN(MaBan),
    FOREIGN KEY (MaNhom) REFERENCES NHOM(MaNhom)
);

CREATE TABLE HOAT_DONG (
    MaHoatDong INT IDENTITY(1,1) PRIMARY KEY,
    TenHoatDong NVARCHAR(200),
    MoTaNgan NVARCHAR(255),
    MoTaChiTiet NVARCHAR(MAX),
    DiaDiem NVARCHAR(255),
    ThoiGianBatDau DATETIME,
    ThoiGianKetThuc DATETIME,
    SoLuong INT,
    MaTaiKhoan INT,
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN(MaTaiKhoan)
);

CREATE TABLE DANG_KY_HOAT_DONG (
    MaDangKy INT IDENTITY(1,1) PRIMARY KEY,
    MaHoatDong INT,
    MaNguoiDung INT,
    ThoiDiemDangKy DATETIME DEFAULT GETDATE(),
    TrangThai NVARCHAR(50),
    FOREIGN KEY (MaHoatDong) REFERENCES HOAT_DONG(MaHoatDong),
    FOREIGN KEY (MaNguoiDung) REFERENCES NGUOI_DUNG(MaNguoiDung)
);

CREATE TABLE THONG_BAO (
    MaThongBao INT IDENTITY(1,1) PRIMARY KEY,
    TieuDe NVARCHAR(255),
    NoiDung NVARCHAR(MAX),
    MaNguoiTao INT,
    DoiTuongNhan NVARCHAR(50),1
    MaBanNhan INT NULL,
    MaNhomNhan INT NULL,
    ThoiGianTao DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (MaNguoiTao) REFERENCES TAI_KHOAN(MaTaiKhoan),
    FOREIGN KEY (MaBanNhan) REFERENCES BAN(MaBan),
    FOREIGN KEY (MaNhomNhan) REFERENCES NHOM(MaNhom)
);

CREATE TABLE NGUOI_NHAN_THONG_BAO (
    MaBanGhi INT IDENTITY(1,1) PRIMARY KEY,
    MaThongBao INT,
    MaNguoiDung INT,
    DaDoc BIT DEFAULT 0,
    FOREIGN KEY (MaThongBao) REFERENCES THONG_BAO(MaThongBao),
    FOREIGN KEY (MaNguoiDung) REFERENCES NGUOI_DUNG(MaNguoiDung)
);

CREATE TABLE PHAN_HOI (
    MaPhanHoi INT IDENTITY(1,1) PRIMARY KEY,
    MaNguoiGui INT,
    TieuDe NVARCHAR(255),
    NoiDung NVARCHAR(MAX),
    TrangThai NVARCHAR(50),
    ThoiGianGui DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (MaNguoiGui) REFERENCES NGUOI_DUNG(MaNguoiDung)
);

CREATE TABLE DON_DANG_KY_BAN (
    MaDon INT IDENTITY(1,1) PRIMARY KEY,
    MaNguoiDangKy INT,
    MaBan INT,
    TrangThai NVARCHAR(50),
    ThoiGianDangKy DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (MaNguoiDangKy) REFERENCES NGUOI_DUNG(MaNguoiDung),
    FOREIGN KEY (MaBan) REFERENCES BAN(MaBan)
);
